apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17msus9dylkjcdgdyjnsp9g0llaxeu3ew9vhu9p4wpe7w0rhtjdpscffqdm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeFFEK250T3E5Y0dyeVFn
            N0hNUnVrL3VLMU5WYUVTZDMycG9na1liY1JNCnJXU1JqUFJaMkRHR3ZNTkV2ei9R
            THJWLzNtZnhzTWNnSUNkdUdhL2p0MEkKLS0tIHJGVHRzaWRUMVBReHBIWUpoWW1X
            aTFmRDRPQlhCb2NoTStMNndoU05CUDgKa0P6t5pjVGV5Q1lUP0H+3Sx+2jP8Np/L
            hWDbLSPMG8eNdDIXC95iSYTYhUuePUadk8Q4GOM9epMrFjPk+Nn0sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T19:03:05Z"
    mac: ENC[AES256_GCM,data:I++LljzsJgjXmFsryzyE9J2YohjdhP0kqu/FXZ/8d4zxcShyLPHqFG8pZfMcAax/+ZEU+iIbEs4x16AYElGCAqkP3b3/OMP8WDLyuoRjHsezU4dzkZtAb4mfp9WEvpXC4YHEVQj2j6mtF5fglEKh006DRXTIbxBy6RigiqEHraM=,iv:n7xOj+EHb55qI8JukGplrGlsaEdVycFl+CuOmkaE4/4=,tag:wWGSXlInkl2u9GgnPWbAvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
