apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:8o6UO/9mxA44lojklo/yMoK3+IxiJmKNv/ZCNTfuVQ6RQ9A7cJj0miUGGepuEJHR4MINAdBnX6yesEhv1HJWyceilah8wvx4dOgeHf/mbmkY,iv:Fy4ysTZMJ5fQy5PKeJ2h5hK5WF+IKW7eoZGfyomZ3E4=,tag:Dj7jU9ghoTn+4U3LtY5Lbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17msus9dylkjcdgdyjnsp9g0llaxeu3ew9vhu9p4wpe7w0rhtjdpscffqdm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaFZlVCsvbk5VUy9mbFl2
            eVV5Vk56Kzd3YjQ4ZlFMbmFFR3hCTEtod2hNCkg5NGhyRTd0M1FIOGdsUDV6RitP
            MXZGSGhMbXJjTG5PNmhrRGZPRVpKTlkKLS0tIGZ2UkZ3VzVHRkcyY2ZzeklSTkMx
            bU4rVTBJWW1FTUlBUnhNV0lsamhOS2MKJ85wXd1lsvjyorxnUg3+vVN/VBM76imJ
            t0VVy9Qt5FUKUmf09fMzrtW/j2vsK0WmXBBe7CgtxOervTR38t7WYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T20:13:34Z"
    mac: ENC[AES256_GCM,data:qxyCjANSeQV+jKpZx9VmL4d4zpz663VIdu8KvVHZqVgT31UwZz2nBj84QZ3sVUXLyW1DaRRYsxbPpZYDpHC5hNOr/CIxdK/sF9r7VNigI6o1BLPOS1bBjqbzwYwhrftojTeB3Grd7Ps76px3cnwXxh43nBPRSwBgzEoJrYSlH5g=,iv:M92CW8tBqhos5+s37twiFmV32lETwylNxyck4SC6tDo=,tag:KfAb4KJj3B7j9XSgZckexQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
