apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:kCd3aIcree04IVezVbFGlfENAO9FQMXVIisQWvsIK30=,iv:1K2JlLVnUoccLN6diaHOTydtopgxt7t0lVl19Zyd320=,tag:X782SXy70VmdV3GoAWFqBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17msus9dylkjcdgdyjnsp9g0llaxeu3ew9vhu9p4wpe7w0rhtjdpscffqdm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByL0dKQjk2UHlXNVFCeVdQ
            d0NuMFdqcmEyclVUVEh0VVJ2UzJpSXlvdzBFCnpWeG55L1ZldWtIWmtGSXFPTUVm
            UDdQaTVPa3RUankrMnp6dG1jYWtOamMKLS0tIGFjL3R3WktlOEZKSEZrT3NLOEt4
            a3p4T25CVXpXenVvenpPUTYxNWtJT0EKTNUR141ihs871s5ALrKHBtr9tZPxr1CP
            vTtCWkPBURIUpEmBOmoL2wl/J7uGE6cUUdDi1zd8DbDx5J5bEuTLaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T00:33:24Z"
    mac: ENC[AES256_GCM,data:uHLJKpUfUXaSqI36cSxoPczkOjHbBDjN6HT/kQ9iLC8uMiAMaELEMnlNNQcewOi+otYE0nWT38fTPFgNWcqxAiruavs8T4iavMckXVh8LODFEvSWzQjnTlexQetrmjbsT09IY3Nzps2OYsbNC6cqYUGgtK4RjoAheI9uOxctA94=,iv:WAlXLqMhe3TvB1rryjUMHy7IHHRGh2V7uOJqtZRX6Gs=,tag:Safoc9t0TLJzWVyczTfszQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
