apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:3Nm5fXZbqxFt9ar0Fqy8MAp6YMCyVfSY/Xh6hAcqAUA=,iv:i9JXt84g7vmHJiU2FV4qpJZ0irKI+JuMd7vSzOkizPE=,tag:Gb3ecR6VAh0OCkAhI5ixOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17msus9dylkjcdgdyjnsp9g0llaxeu3ew9vhu9p4wpe7w0rhtjdpscffqdm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL2V0cDZhemx1WlRwQ0Iy
            YzZodHRxYkZBRVhJN01DUW9POVlUbEhNcDJFCjdRSDZ0NXlZTnkwaWFxV1UwQnZl
            M0RUM1ZPVHVoTS9aa1lSVGNqNVRsWnMKLS0tIDAwbnpBVlFrMDVMc0ljUjJWRnRr
            TER6Y1kvUlFhZlloOU9nd21GcjE4SVEKMd1CTfzRtAGzIyfIKwAHFEDl0dBaEIjK
            g8+cIYB062Mqw4nzVJmDhKBvhOOxVJ/5/aPuJHDf7WwP2Sl1HW/xrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T18:16:12Z"
    mac: ENC[AES256_GCM,data:lrB+2w68em7T9tDm6fKX5wUR6516XKA7/1C4HE0x+BMcizuorDhbALj35AR6qm3XhDapngsQOXdJaZDMb/KboHcJPszKLeqIyePcpPSaniRv7lqellSnsnVLm7vwwZaQaUzdSrQ8pye94aY174QJE+vWOGR+66AE8mqrwft+e8c=,iv:anly4LjX/eA70FBPdaaIbmUE5n1dBLUxEKS/E8FZnMk=,tag:QZ5qbHLoQZf1LFI8wQFToA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
